CFLAGS = -w -g

CC = gcc 

EXECUTABLE = ShareStack

OBJECTS = Share_Stack_Main.o share_stack.o

ALL = $(OBJECTS) $(EXECUTABLE).exe


$(EXECUTABLE): $(OBJECTS)
	$(CC) $(CFLAGS) $^ -o $@ 
	@echo "generate $@ success."
	del $(OBJECTS)
#if don't want .o file, del them

%.o: %.c
	$(CC) $(CFLAGS) -c $<
	@echo "compile $@ success"

clean:
	del -f $(ALL)
	@echo "del '$(ALL)' success."
